services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_new
    environment:
      MYSQL_ROOT_PASSWORD: hei123
      MYSQL_DATABASE: Kartverket
      MYSQL_USER: root
      MYSQL_PASSWORD: hei123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  kartverket:
    build:
      context: .
      dockerfile: Kartverket/Dockerfile
    image: kartverket
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb_new;Database=Kartverket;User=root;Password=hei123;"
    networks:
      - backend
volumes:
  mariadb_data:
networks:
  backend: